version: 2

models:
  - name: dim_pages
    description: >-
      Pages dimension
    columns:
      - name: page_url
        description: page_url
        tests:
          - not_null
      - name: product_id
        description: The id of product page
      - name: product_name
        description: Name of the product page
      - name: created_at
        description: created date of the page
  - name: dim_products
    description: >-
      Products dimension
    columns:
      - name: product_id
        description: product_id
        tests:
          - not_null
      - name: name
        description: The name of product
      - name: in_stock
        description: If there's product in stock
      - name: quantity
        description: number of items in in stock
        tests:
          - positive_values